### PR TITLE
Fix/masternode UI

### LINKED ISSUE #610: Masternode Count wrong
Open Issue in APP, closed in AIN. #### What happened: Tab Masternodes shows only 898 enabled Masternodes. Maybe the default value from listmasternodes of 1000 is used to display.

#### How to reproduce it (as minimally and precisely as possible):
Open Wallet, click Tab Masternodes

#### What are your environment parameters:
Windows, APP-Version 2.3.0

#### Anything else we need to know?:
It seems same behaviour in MAC APP, some Users reported in Telegram.

mn_count

__Originally posted by @Stonygan in https://github.com/DeFiCh/ain/issues/260__

### PR DESCRIPTION
**Pull request by Stonygan**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
List all MN in UI Tab Masternodes -> ALL. Current only first 1000 enabled MN are displayed. Users confused that they dont find own MN in the list after creating.

#### Which issue(s) does this PR fixes?:
Fixes #610

### CODE REVIEW

File: webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx [hunk 1]
```diff
@@ -8,10 +8,11 @@ import { ALL, MINE } from 'src/constants';
 interface MasterNodeTabsHeaderProps {
   setTab: (tab: string) => void;
   tab: string;
+  setFooterHide: (boolean) => void;
 }
 
 const MasterNodeTabsHeader = (props: MasterNodeTabsHeaderProps) => {
-  const { setTab, tab } = props;
+  const { setTab, tab, setFooterHide } = props;
```
Comment (thedoublejay) [inline webapp/src/containers/MasternodesPage/components/MasterNodeTabHeader/index.tsx:15]: hi @Stonygan, wanted to ask why did you add this setFooterHide for some methods? thanks

**Review by thedoublejay — CHANGES_REQUESTED** [review]

**Review by monstrobishi — APPROVED** [review]

**Review by thedoublejay — APPROVED** [review]
